#!/usr/bin/env python3
"""
MCP 环境初始化脚本 (Linux / macOS / Windows 通用)

从 env.json 读取密钥配置，支持两个独立步骤：
  - Env      : 设置环境变量（写入 shell 配置文件或仅导出提示）
  - Generate : 从 mcp.template.json 模板生成 mcp.json
  - All      : 依次执行以上两步（默认）

用法:
  python3 scripts/init-mcp-env.py -a Env
  python3 scripts/init-mcp-env.py -a Generate
  python3 scripts/init-mcp-env.py -a All
  python3 scripts/init-mcp-env.py -a Env --scope user --force
  python3 scripts/init-mcp-env.py -a Generate -f ./custom-env.json
"""

import argparse
import json
import os
import re
import sys
from pathlib import Path

COLOR_CYAN = "\033[96m"
COLOR_GREEN = "\033[92m"
COLOR_YELLOW = "\033[93m"
COLOR_RED = "\033[91m"
COLOR_DARKGRAY = "\033[90m"
COLOR_RESET = "\033[0m"

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent

MARKER_START = "# >>> MCP ENV START (auto-generated by init-mcp-env.py) >>>"
MARKER_END = "# <<< MCP ENV END <<<"


def read_env_config(env_file: Path, silent: bool = False) -> dict:
    if not env_file.exists():
        print(f"{COLOR_RED}[ERROR] Config file not found: {env_file}{COLOR_RESET}")
        print()
        print("Steps:")
        print("  1. Copy env.example.json to env.json")
        print("  2. Fill in real API Keys in env.json")
        print("  3. Re-run this script")
        sys.exit(1)
    if not silent:
        print(f"{COLOR_GREEN}[READ] {env_file}{COLOR_RESET}")
    with open(env_file, "r", encoding="utf-8-sig") as f:
        return json.load(f)


def get_env_entries(env_config: dict) -> list[tuple[str, str]]:
    entries = []
    for key, value in env_config.items():
        if key == "_description":
            continue
        value_str = str(value).strip() if value is not None else ""
        if not value_str:
            os_value = os.environ.get(key, "").strip()
            if os_value:
                value_str = os_value
                print(
                    f"  {COLOR_DARKGRAY}[FALLBACK] {key} 取自 OS 环境变量{COLOR_RESET}"
                )
        if value_str:
            entries.append((key, value_str))
    return entries


def mask_value(v: str) -> str:
    if len(v) > 20:
        return v[:8] + "..." + v[-8:]
    return v


def invoke_env_step(env_config: dict, scope: str, force: bool) -> dict[str, str]:
    scope_labels = {
        "process": "Current session (lost on terminal close)",
        "user": "Current user (persistent, write to shell rc)",
    }

    print(f"{COLOR_CYAN}========================================{COLOR_RESET}")
    print(f"{COLOR_CYAN}  Step: Set Environment Variables{COLOR_RESET}")
    print(f"{COLOR_CYAN}========================================{COLOR_RESET}")
    print()

    if scope not in scope_labels:
        print(f"{COLOR_RED}[ERROR] Unknown scope: {scope}. Use 'process' or 'user'.{COLOR_RESET}")
        sys.exit(1)

    print(f"{COLOR_GREEN}Target scope: {scope} ({scope_labels[scope]}){COLOR_RESET}")

    entries = get_env_entries(env_config)
    env_map = {k: v for k, v in entries}

    if scope == "user" and not force:
        print()
        print(f"{COLOR_YELLOW}About to write the following env vars to [{scope}]:{COLOR_RESET}")
        for key, value in entries:
            print(f"  {COLOR_YELLOW}{key} = {mask_value(value)}{COLOR_RESET}")
        print()
        confirm = input("Confirm write? (y/n) ").strip().lower()
        if confirm != "y":
            print(f"{COLOR_RED}Cancelled.{COLOR_RESET}")
            sys.exit(0)

    print()
    print(f"{COLOR_GREEN}Setting env vars...{COLOR_RESET}")

    ok = 0
    for key, value in entries:
        os.environ[key] = value
        print(f"  {COLOR_GREEN}[OK]   {key}{COLOR_RESET}")
        ok += 1

    print()
    print(f"  {COLOR_CYAN}Result: {ok} ok, scope=[{scope}]{COLOR_RESET}")

    if scope == "process":
        print(f"  {COLOR_YELLOW}Note: Env vars only valid in current Python process.{COLOR_RESET}")
        print(f"  {COLOR_YELLOW}      For shell persistence, use: --scope user{COLOR_RESET}")
        print(f"  {COLOR_YELLOW}      Or manually: eval $(python3 scripts/init-mcp-env.py -a Env --export-shell){COLOR_RESET}")

    if scope == "user":
        shell_rc = _detect_shell_rc()
        print(f"  {COLOR_GREEN}Writing to shell config: {shell_rc}{COLOR_RESET}")
        _write_shell_rc(shell_rc, env_map, force)

    print()
    return env_map


def _detect_shell_rc() -> Path:
    shell = os.environ.get("SHELL", "")
    if "zsh" in shell:
        return Path.home() / ".zshrc"
    if "bash" in shell:
        bash_profile = Path.home() / ".bash_profile"
        if bash_profile.exists():
            return bash_profile
        return Path.home() / ".bashrc"
    return Path.home() / ".profile"


def _write_shell_rc(shell_rc: Path, env_map: dict[str, str], force: bool) -> None:
    content = ""
    if shell_rc.exists():
        content = shell_rc.read_text(encoding="utf-8")

    if MARKER_START in content:
        pattern = re.compile(
            re.escape(MARKER_START) + r".*?" + re.escape(MARKER_END),
            re.DOTALL,
        )
        content = pattern.sub("", content)

    lines = [MARKER_START]
    for key, value in sorted(env_map.items()):
        escaped = value.replace("'", "'\\''")
        lines.append(f"export {key}='{escaped}'")
    lines.append(MARKER_END)

    content = content.rstrip("\n") + "\n\n" + "\n".join(lines) + "\n"

    shell_rc.write_text(content, encoding="utf-8")
    print(f"  {COLOR_GREEN}[OK]   Written to {shell_rc}{COLOR_RESET}")
    print(f"  {COLOR_GREEN}Note: New terminals will auto-load these env vars.{COLOR_RESET}")


def invoke_export_shell(env_config: dict) -> None:
    entries = get_env_entries(env_config)
    for key, value in entries:
        escaped = value.replace("'", "'\\''")
        print(f"export {key}='{escaped}'")


def invoke_generate_step(
    env_config: dict,
    template_file: Path,
    output_file: Path,
) -> None:
    print(f"{COLOR_CYAN}========================================{COLOR_RESET}")
    print(f"{COLOR_CYAN}  Step: Generate mcp.json{COLOR_RESET}")
    print(f"{COLOR_CYAN}========================================{COLOR_RESET}")
    print()

    if not template_file.exists():
        print(f"{COLOR_RED}[ERROR] Template file not found: {template_file}{COLOR_RESET}")
        sys.exit(1)

    print(f"{COLOR_GREEN}Template : {template_file}{COLOR_RESET}")
    print(f"{COLOR_GREEN}Output   : {output_file}{COLOR_RESET}")
    print()

    template_content = template_file.read_text(encoding="utf-8")

    replaced = 0
    entries = get_env_entries(env_config)
    for key, value in entries:
        placeholder = "${" + key + "}"
        if placeholder in template_content:
            template_content = template_content.replace(placeholder, value)
            print(f"  {COLOR_GREEN}[REPLACED] {placeholder}{COLOR_RESET}")
            replaced += 1

    remaining = re.findall(r"\$\{(\w+)\}", template_content)
    if remaining:
        print()
        print(f"  {COLOR_YELLOW}[WARN] Unresolved placeholders (missing in env.json):{COLOR_RESET}")
        seen = sorted(set(remaining))
        for p in seen:
            print(f"    - ${{{p}}}")

    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(template_content, encoding="utf-8")

    print()
    print(f"  {COLOR_CYAN}Result: {replaced} placeholder(s) replaced, output={output_file}{COLOR_RESET}")
    print()


def main():
    parser = argparse.ArgumentParser(
        description="MCP Env Init - Set environment variables and generate mcp.json from template",
    )
    parser.add_argument(
        "-a", "--action",
        choices=["Env", "Generate", "All", "ExportShell"],
        default="All",
        help="Action: Env (env vars only), Generate (mcp.json only), All (both), ExportShell (print export statements)",
    )
    parser.add_argument(
        "-f", "--env-file",
        default=str(PROJECT_ROOT / "env.json"),
        help="Path to env.json (default: project_root/env.json)",
    )
    parser.add_argument(
        "--template-file",
        default=str(PROJECT_ROOT / "agents" / "mcp" / "mcp.template.json"),
        help="Path to mcp.template.json",
    )
    parser.add_argument(
        "--output-file",
        default=str(PROJECT_ROOT / "agents" / "mcp" / "mcp.json"),
        help="Output path for generated mcp.json",
    )
    parser.add_argument(
        "--scope",
        choices=["process", "user"],
        default="process",
        help="Env var scope: process (current session) or user (persistent)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Skip confirmation prompts",
    )

    args = parser.parse_args()

    env_file = Path(args.env_file)
    template_file = Path(args.template_file)
    output_file = Path(args.output_file)

    env_config = read_env_config(env_file, silent=(args.action == "ExportShell"))

    if args.action == "ExportShell":
        invoke_export_shell(env_config)
        return

    print(f"{COLOR_CYAN}========================================{COLOR_RESET}")
    print(f"{COLOR_CYAN}  MCP Env Init{COLOR_RESET}")
    print(f"{COLOR_CYAN}========================================{COLOR_RESET}")
    print()

    if args.action in ("Env", "All"):
        invoke_env_step(env_config, args.scope, args.force)

    if args.action in ("Generate", "All"):
        invoke_generate_step(env_config, template_file, output_file)

        opencode_template = PROJECT_ROOT / "ide" / "opencode" / "opencode.template.json"
        opencode_output = PROJECT_ROOT / "ide" / "opencode" / "opencode.json"
        if opencode_template.exists():
            invoke_generate_step(env_config, opencode_template, opencode_output)

        codex_auth_template = PROJECT_ROOT / "ide" / "codex" / "auth.template.json"
        codex_auth_output = PROJECT_ROOT / "ide" / "codex" / "auth.json"
        if codex_auth_template.exists():
            invoke_generate_step(env_config, codex_auth_template, codex_auth_output)

    print(f"{COLOR_CYAN}========================================{COLOR_RESET}")
    print(f"{COLOR_CYAN}  Done.{COLOR_RESET}")
    print(f"{COLOR_CYAN}========================================{COLOR_RESET}")
    print()


if __name__ == "__main__":
    main()
